package main

//Generated by webgen.py
const webpage = `
<!DOCTYPE html>
<html>
  <head>
    <title>Freehold Sync</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	</head>
<body>
<div id="ractives">
	test			
</div>

</body>
</html>
`
